version: '3.4'

services:
  postgres:
    image: postgres:10.1
    volumes:
      - shop_demo_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ShopDemo
      - POSTGRES_USER=shop_demo
      - POSTGRES_DB=shop_demo
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - service_internal
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/fae-shop-demo
    environment:
      - TZ=Europe/Berlin
      - SHOP_DEMO_DB=postgres
      - SHOP_DEMO_DB_NAME=shop_demo
      - SHOP_DEMO_DB_USER=shop_demo
      - SHOP_DEMO_DB_PW=ShopDemo
    depends_on:
      - postgres
    networks:
      - service_internal
      - fae_backend
volumes:
  shop_demo_db: {}
networks:
  service_internal:
  fae_backend:
    external: true
