version: '3.4'

services:
  postgres:
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  springboot-service:
    image: docker.nexus.archi-lab.io/archilab/fae-shop-demo:${BUILD_ID}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - fae_backend
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
networks:
  fae_backend:
    external: true
